# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++
# Build steps
before_install:
  - chmod +x build.sh
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

script:
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles"
  - make
  - make test

addons:
  apt:
    sources:
     # cmake 3.2.3 / doxygen 1.8.3
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data